server {
    listen 80;
    server_name _;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    root /usr/share/nginx/html;
    index index.html;

    location ^~ /media/ {
        alias /var/www/media/;

        expires max;
        add_header Cache-Control "public, immutable";
        access_log off;

        try_files $uri =404;
    }

    # 2. ПРОКСИРОВАНИЕ НА БЭКЕНД (GRANIAN)
    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://unix:/tmp/sockets/granian.sock;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering on;
        proxy_buffers 16 16k;
        proxy_buffer_size 32k;
    }

    location ~* \.(?:css|js|mjs|map|ico|png|jpg|jpeg|gif|svg|webp|woff|woff2|ttf|eot)$ {
        try_files $uri =404;

        expires max;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    # 4. РОУТИНГ SPA (REACT)
    location / {
        try_files $uri $uri/ /index.html;

        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
}
