server {
    listen 80;
    server_name _;

    # Включаем эффективную отдачу файлов на уровне ядра (очень важно для медиа и статики)
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    # Корневая папка для фронтенда
    root /usr/share/nginx/html;
    index index.html;

    # 1. РАЗДАЧА МЕДИАФАЙЛОВ
    # Используем модификатор ^~, чтобы Nginx прекратил поиск по регулярным выражениям.
    # Если этого не сделать, регулярка со статикой перехватит .jpg/.png и будет искать их в папке фронтенда (отдавая 404).
    location ^~ /media/ {
        alias /var/www/media/;
        
        # Строгое кеширование (браузер не будет даже спрашивать Nginx, изменился ли файл)
        expires max;
        add_header Cache-Control "public, immutable";
        access_log off;
        
        # Если файла нет — сразу 404, без попытки отдать index.html
        try_files $uri =404;
    }

    # 2. ПРОКСИРОВАНИЕ НА БЭКЕНД (GRANIAN)
    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://unix:/tmp/sockets/granian.sock;
        
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Оптимизация буферов. Granian работает очень быстро, 
        # Nginx должен успевать складывать его ответы в память.
        proxy_buffering on;
        proxy_buffers 16 16k;
        proxy_buffer_size 32k;
    }

    # 3. КЕШИРОВАНИЕ СТАТИКИ ФРОНТЕНДА
    location ~* \.(?:css|js|mjs|map|ico|png|jpg|jpeg|gif|svg|webp|woff|woff2|ttf|eot)$ {
        try_files $uri =404;
        
        # Vite хеширует имена файлов (напр. index-DUM9A0Zo.js), 
        # поэтому их можно смело кешировать навсегда.
        expires max;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    # 4. РОУТИНГ SPA (REACT)
    location / {
        try_files $uri $uri/ /index.html;
        
        # ЗАПРЕЩАЕМ кешировать index.html!
        # Иначе при деплое новой версии юзеры будут видеть старый кешированный html 
        # со ссылками на старые JS/CSS файлы.
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
}