services:
  postgres:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d database"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile.app
    container_name: backend
    environment:
      DATABASE__URL__DRIVER: postgresql+asyncpg
      DATABASE__URL__HOST: postgres
      DATABASE__URL__USERNAME: user
      DATABASE__URL__PASSWORD: password
      DATABASE__URL__PORT: "5432"
      DATABASE__URL__DATABASE: database
    volumes:
      - ./backend/config.yaml:/app/config.yaml:ro
      - /tmp/my-project-sockets:/tmp/sockets
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  migrate:
    build:
      context: ./backend
      dockerfile: dockerfile.migrate
    container_name: migrate
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@postgres:5432/database
    depends_on:
      postgres:
        condition: service_healthy

  parser:
    build:
      context: ./backend
      dockerfile: dockerfile.script
    container_name: tmdb_parser
    environment:
      PYTHONUNBUFFERED: 1
      DATABASE_URL: postgresql+asyncpg://user:password@postgres:5432/database
      TMDB_API_KEY: d5af69280dd7493bb219e8f9c2c0e24c
    volumes:
      - ./films.txt:/app/films.txt
      - media_data:/app/images
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - /tmp/my-project-sockets:/tmp/sockets
      - media_data:/var/www/media:ro

volumes:
  media_data: