services:
  postgres:
    build:
      context: ./Postgres
      dockerfile: Dockerfile
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    deploy:
      resources:
        limits:
          cpus: '6.0'
          memory: 6G
        reservations:
          cpus: '6.0'
          memory: 6G
    command: >
      postgres -c max_connections=150
               -c shared_buffers=1536MB
               -c effective_cache_size=4GB
               -c maintenance_work_mem=512MB
               -c work_mem=16MB
               -c checkpoint_completion_target=0.9
               -c wal_buffers=16MB
               -c default_statistics_target=100
               -c random_page_cost=1.1
               -c effective_io_concurrency=200
               -c max_worker_processes=6
               -c max_parallel_workers_per_gather=3
               -c max_parallel_workers=6
    volumes:
      - ./Postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d database" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
