"""Initial migration.

Revision ID: 7fc1378747b8
Revises:
Create Date: 2026-05-06 15:12:10.084572

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import HALFVEC

# revision identifiers, used by Alembic.
revision: str = '7fc1378747b8'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text('CREATE EXTENSION IF NOT EXISTS vector'))
    op.create_table(
        'files',
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('year_of_release', sa.DateTime(), nullable=False),
        sa.Column('genres', sa.ARRAY(sa.String()), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_files')),
    )
    op.create_index(
        'ix_movie_genres_gin',
        'files',
        ['genres'],
        unique=False,
        postgresql_using='gin',
    )
    op.create_table(
        'vectors',
        sa.Column('file_id', sa.Uuid(), nullable=False),
        sa.Column('vector', HALFVEC(dim=1024), nullable=False),
        sa.Column('model', sa.String(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['file_id'], ['files.id'], name=op.f('fk_vectors_file_id_files')
        ),
        sa.PrimaryKeyConstraint('file_id', 'id', name=op.f('pk_vectors')),
    )
    op.create_index(
        'idx_vectors_hnsw_cosine',
        'vectors',
        ['vector'],
        unique=False,
        postgresql_using='hnsw',
        postgresql_with={'m': 16, 'ef_construction': 64},
        postgresql_ops={'vector': 'halfvec_cosine_ops'},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'idx_vectors_hnsw_cosine',
        table_name='vectors',
        postgresql_using='hnsw',
        postgresql_with={'m': 16, 'ef_construction': 64},
        postgresql_ops={'vector': 'halfvec_cosine_ops'},
    )
    op.drop_table('vectors')
    op.drop_index(
        'ix_movie_genres_gin', table_name='files', postgresql_using='gin'
    )
    op.drop_table('files')
    op.execute(sa.text('DROP EXTENSION IF EXISTS vector'))
    # ### end Alembic commands ###
