"""user.

Revision ID: 260a9e8a9741
Revises: ea19d992409e
Create Date: 2026-05-14 19:12:26.669805

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '260a9e8a9741'
down_revision: str | Sequence[str] | None = 'ea19d992409e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('password_hash', sa.String(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
        sa.UniqueConstraint('email', name=op.f('uq_users_email')),
        sa.UniqueConstraint('name', name=op.f('uq_users_name')),
    )

    op.create_table(
        'association_table',
        sa.Column('users_id', sa.Uuid(), nullable=True),
        sa.Column('films_id', sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ['films_id'],
            ['films.id'],
            name=op.f('fk_association_table_films_id_films'),
        ),
        sa.ForeignKeyConstraint(
            ['users_id'],
            ['users.id'],
            name=op.f('fk_association_table_users_id_users'),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_table')
    op.drop_table('users')
    # ### end Alembic commands ###
